TYPES = ["HARD", "SOFT", "HARD_AND_SOFT", "OTHER"]
STATUSES = ["ACTIVE", "PENDING", "STOPPED", "COMPLETED", "ARCHIVED"]
CATEGORY = ["UPPER_LEVEL_OR_PRIVATE_OFFICE", "INTERNAL_PROJECTS", "OTO",
            "ROLLER_SHUTTER_AUTOMATICS", "MIDDLE_NETWORK_LAYER", "COMMUNICATION_TECHNOLOGIES",
            "SMART_HOUSE", "WATER_METERING", "GAS_METERING", "ELECTRICITY_METERING", "OTHER"]
